import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import AvartarMe from "./components/AvartarMe";

export const metadata: Metadata = {
  title: "Phat Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={"dark: bg-slate-800"}>
        <Navbar />
        <AvartarMe />
        {children}
      </body>
    </html>
  );
}
