export const ROUTES = {
  HOME_PAGE: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  REGISTER_TERM: '/register/term',
  REGISTER_TERM_SNS: '/register/term/sns',
  REGISTER_CREATE_USER: '/register/create-user',
  REGISTER_VERIFY: '/register/verify',
  FORGOT_PASSWORD: '/forgot-password',
  FORGOT_PASSWORD_RESET: '/forgot-password/reset',
  FORGOT_PASSWORD_COMPLETE: '/forgot-password/reset/complete',
  FORGOT_PASSWORD_CONFIRM: '/forgot-password/confirm',
  RANKING: '/ranking',
  SERIES: '/series',
  MY_BOOKSHELF: '/my-bookshelf',
  MY_PAGE: '/my-page',
  BUY_POINT: '/buy-point',
  HELP_CENTER: '/help-center',
  MY_PRESENT: '/my-present',
  TERM: '/term',
  PRIVACY_POLICY: '/privacy-policy',
  COMMERCIAL_TRANSACTION_LAW: '/commercial-transaction-law',
  CART: '/cart',
  SEARCH: '/search?${0}=${1}',
  NOT_FOUND: '/not-found',
  COMIC_PREVIEW: '/comic-preview',
  CHAPTER_PREVIEW: '/chapter-preview',
  VOLUME_PREVIEW: '/volume-preview',
  COMIC: '/comic',
  COMIC_DETAIL: '/comic/${0}',
  VOLUME: '/volume',
  VOLUME_DETAIL: '/comic/${0}/volume/${1}',
  CHAPTER_DETAIL: '/comic/${0}/chapter/${1}',
  PURCHASE: '/comic/${0}/volume-purchase',
  VIEWER: '/viewer',
  VOLUMES_LIST: '/comic/${0}/volume-list',
};

export const LINK = {
  x: 'https://x.com/LezhinComics_JP',
  instagram: 'https://www.instagram.com/lezhincomics_jp/',
  youtube: 'https://www.youtube.com/@xbeltoon7425',
  blog: 'https://lezhin.blog.jp/',
};
